const control_ir = @import("control_ir");
const std = @import("std");

/// Compiler classifications for generated continuation constructors.
pub const ConstructorKind = enum {
    entry,
    segment_entry,
    loop_header,
    await_effect,
    call_return,
    after_handler,
    caller_fuel_yield,
    terminal_handoff,
};

/// One exact ordered field in a continuation environment.
pub const EnvironmentField = struct {
    value: control_ir.ValueId,
    value_type: control_ir.ValueType,
};

/// Target-neutral relations admitted by the local integer-predicate algebra.
pub const IntegerRelation = enum {
    equal,
    not_equal,
    less_than,
    less_equal,
    greater_than,
    greater_equal,
};

/// Bounded constructor-local path facts generated by the compiler.
pub const InvariantTerm = union(enum) {
    boolean: struct {
        value: control_ir.ValueId,
        expected: bool,
    },
    integer_zero: struct {
        value: control_ir.ValueId,
        equal: bool,
    },
    integer_relation: struct {
        left: control_ir.ValueId,
        right: control_ir.ValueId,
        relation: IntegerRelation,
        expected: bool,
    },
    sum_case: struct {
        value: control_ir.ValueId,
        case_index: u16,
        equal: bool,
    },

    fn addRequired(self: InvariantTerm, required: anytype) void {
        switch (self) {
            .boolean => |term| _ = required.insert(term.value),
            .integer_zero => |term| _ = required.insert(term.value),
            .integer_relation => |term| {
                _ = required.insert(term.left);
                _ = required.insert(term.right);
            },
            .sum_case => |term| _ = required.insert(term.value),
        }
    }

    fn eql(self: InvariantTerm, other: InvariantTerm) bool {
        return switch (self) {
            .boolean => |term| switch (other) {
                .boolean => |other_term| term.value == other_term.value and
                    term.expected == other_term.expected,
                .integer_zero, .integer_relation, .sum_case => false,
            },
            .integer_zero => |term| switch (other) {
                .boolean => false,
                .integer_zero => |other_term| term.value == other_term.value and
                    term.equal == other_term.equal,
                .integer_relation, .sum_case => false,
            },
            .integer_relation => |term| switch (other) {
                .boolean, .integer_zero => false,
                .integer_relation => |other_term| term.left == other_term.left and
                    term.right == other_term.right and
                    term.relation == other_term.relation and
                    term.expected == other_term.expected,
                .sum_case => false,
            },
            .sum_case => |term| switch (other) {
                .boolean, .integer_zero, .integer_relation => false,
                .sum_case => |other_term| term.value == other_term.value and
                    term.case_index == other_term.case_index and
                    term.equal == other_term.equal,
            },
        };
    }
};

/// Minimal target-neutral values needed to evaluate the invariant algebra.
pub const InvariantValue = union(enum) {
    boolean: bool,
    signed: i64,
    unsigned: u64,
    sum_case: u16,
};

/// One value binding supplied to constructor-local invariant evaluation.
pub const InvariantBinding = struct {
    value: control_ir.ValueId,
    contents: InvariantValue,
};

/// RNF synthesis and local-validation failures.
pub const Error = control_ir.ValidationError || error{
    TooManyConstructors,
    TooManyEnvironmentFields,
    TooManyInvariantTerms,
    MissingInvariantValue,
    InvalidInvariantValue,
    InvariantViolation,
};

fn bindingFor(
    bindings: []const InvariantBinding,
    value: control_ir.ValueId,
) ?InvariantValue {
    for (bindings) |binding| {
        if (binding.value == value) return binding.contents;
    }
    return null;
}

/// Evaluate one admitted fixed-width integer relation.
pub fn integerRelationHolds(
    left: anytype,
    right: @TypeOf(left),
    relation: IntegerRelation,
) bool {
    return switch (relation) {
        .equal => left == right,
        .not_equal => left != right,
        .less_than => left < right,
        .less_equal => left <= right,
        .greater_than => left > right,
        .greater_equal => left >= right,
    };
}

fn evaluate(term: InvariantTerm, bindings: []const InvariantBinding) Error!void {
    const accepted = switch (term) {
        .boolean => |predicate| switch (bindingFor(
            bindings,
            predicate.value,
        ) orelse return error.MissingInvariantValue) {
            .boolean => |actual| actual == predicate.expected,
            .signed, .unsigned, .sum_case => return error.InvalidInvariantValue,
        },
        .integer_zero => |predicate| switch (bindingFor(
            bindings,
            predicate.value,
        ) orelse return error.MissingInvariantValue) {
            .boolean, .sum_case => return error.InvalidInvariantValue,
            .signed => |actual| (actual == 0) == predicate.equal,
            .unsigned => |actual| (actual == 0) == predicate.equal,
        },
        .integer_relation => |predicate| blk: {
            const left = bindingFor(bindings, predicate.left) orelse
                return error.MissingInvariantValue;
            const right = bindingFor(bindings, predicate.right) orelse
                return error.MissingInvariantValue;
            const actual = switch (left) {
                .boolean, .sum_case => return error.InvalidInvariantValue,
                .signed => |left_value| switch (right) {
                    .signed => |right_value| integerRelationHolds(
                        left_value,
                        right_value,
                        predicate.relation,
                    ),
                    .boolean, .unsigned, .sum_case => return error.InvalidInvariantValue,
                },
                .unsigned => |left_value| switch (right) {
                    .unsigned => |right_value| integerRelationHolds(
                        left_value,
                        right_value,
                        predicate.relation,
                    ),
                    .boolean, .signed, .sum_case => return error.InvalidInvariantValue,
                },
            };
            break :blk actual == predicate.expected;
        },
        .sum_case => |predicate| switch (bindingFor(
            bindings,
            predicate.value,
        ) orelse return error.MissingInvariantValue) {
            .sum_case => |actual| (actual == predicate.case_index) ==
                predicate.equal,
            .boolean, .signed, .unsigned => return error.InvalidInvariantValue,
        },
    };
    if (!accepted) return error.InvariantViolation;
}

/// One bounded program-specific continuation constructor.
pub fn Constructor(
    comptime maximum_environment_fields: usize,
    comptime maximum_invariant_terms: usize,
) type {
    return struct {
        const Self = @This();

        id: u32,
        kind: ConstructorKind,
        source_block: control_ir.BlockId,
        resume_target: ?control_ir.BlockId = null,
        environment: [maximum_environment_fields]EnvironmentField = undefined,
        environment_len: usize = 0,
        invariants: [maximum_invariant_terms]InvariantTerm = undefined,
        invariant_len: usize = 0,

        /// Borrow the exact ordered environment schema.
        pub fn environmentFields(self: *const Self) []const EnvironmentField {
            return self.environment[0..self.environment_len];
        }

        /// Borrow the constructor-local invariant conjunction.
        pub fn invariantTerms(self: *const Self) []const InvariantTerm {
            return self.invariants[0..self.invariant_len];
        }

        /// Validate only the bounded local path facts attached to this constructor.
        pub fn validateInvariant(
            self: *const Self,
            bindings: []const InvariantBinding,
        ) Error!void {
            for (self.invariantTerms()) |term| try evaluate(term, bindings);
        }
    };
}

fn constructorKindForRole(role: control_ir.BlockRole) ConstructorKind {
    return switch (role) {
        .segment => .segment_entry,
        .loop_header => .loop_header,
        .call_return => .call_return,
        .after_handler => .after_handler,
        .terminal_handoff => .terminal_handoff,
    };
}

fn constructorKindForSuspension(
    kind: control_ir.SuspensionKind,
) ConstructorKind {
    return switch (kind) {
        .effect => .await_effect,
        .call => .call_return,
        .explicit_yield, .caller_fuel => .caller_fuel_yield,
    };
}

fn edgeTargets(edge: control_ir.Edge, target: control_ir.BlockId) bool {
    return edge.target == target;
}

fn definingInstruction(
    program: control_ir.Program,
    value: control_ir.ValueId,
) ?control_ir.Instruction {
    for (program.blocks) |block| {
        for (block.instructions) |instruction| {
            if (instruction.result == value) return instruction;
        }
    }
    return null;
}

fn factForBranch(
    program: control_ir.Program,
    branch: control_ir.Branch,
    target: control_ir.BlockId,
) ?InvariantTerm {
    const selected_edge = if (edgeTargets(branch.then_edge, target))
        branch.then_edge
    else if (edgeTargets(branch.else_edge, target))
        branch.else_edge
    else
        return null;
    const expected = edgeTargets(branch.then_edge, target);
    const target_block = program.blocks[selected_edge.target];
    const Projection = struct {
        fn value(
            edge: control_ir.Edge,
            block: control_ir.Block,
            source: control_ir.ValueId,
        ) control_ir.ValueId {
            for (edge.arguments, block.parameters) |argument, parameter| {
                switch (argument) {
                    .value => |value_id| {
                        if (value_id == source) return parameter;
                    },
                    .@"resume" => {},
                }
            }
            return source;
        }
    };

    if (definingInstruction(program, branch.condition)) |instruction| {
        if (instruction.kind == .compare_eq_zero and instruction.operands.len == 1) {
            return .{ .integer_zero = .{
                .value = Projection.value(
                    selected_edge,
                    target_block,
                    instruction.operands[0],
                ),
                .equal = expected,
            } };
        }
        switch (instruction.operation) {
            .integer_equal,
            .integer_not_equal,
            .integer_less_than,
            .integer_less_equal,
            .integer_greater_than,
            .integer_greater_equal,
            => return .{ .integer_relation = .{
                .left = Projection.value(
                    selected_edge,
                    target_block,
                    instruction.operands[0],
                ),
                .right = Projection.value(
                    selected_edge,
                    target_block,
                    instruction.operands[1],
                ),
                .relation = switch (instruction.operation) {
                    .integer_equal => .equal,
                    .integer_not_equal => .not_equal,
                    .integer_less_than => .less_than,
                    .integer_less_equal => .less_equal,
                    .integer_greater_than => .greater_than,
                    .integer_greater_equal => .greater_equal,
                    else => unreachable,
                },
                .expected = expected,
            } },
            .sum_tag_is => |case_index| return .{ .sum_case = .{
                .value = Projection.value(
                    selected_edge,
                    target_block,
                    instruction.operands[0],
                ),
                .case_index = case_index,
                .equal = expected,
            } },
            .optional_is_some => return .{ .sum_case = .{
                .value = Projection.value(
                    selected_edge,
                    target_block,
                    instruction.operands[0],
                ),
                .case_index = 1,
                .equal = expected,
            } },
            else => {},
        }
    }
    return .{ .boolean = .{
        .value = Projection.value(
            selected_edge,
            target_block,
            branch.condition,
        ),
        .expected = expected,
    } };
}

fn immediateInvariant(
    program: control_ir.Program,
    target: control_ir.BlockId,
    reachability: anytype,
) ?InvariantTerm {
    var result: ?InvariantTerm = null;
    var predecessor_count: usize = 0;
    for (program.blocks) |block| {
        if (!reachability.contains(block.id)) continue;
        switch (block.terminator) {
            .branch => |branch| {
                if (!edgeTargets(branch.then_edge, target) and
                    !edgeTargets(branch.else_edge, target)) continue;
                const fact = factForBranch(program, branch, target) orelse return null;
                predecessor_count += 1;
                if (result) |existing| {
                    if (!existing.eql(fact)) return null;
                } else {
                    result = fact;
                }
            },
            .jump => |edge| {
                if (edgeTargets(edge, target)) return null;
            },
            .@"suspend" => |suspension| {
                if (edgeTargets(suspension.continuation, target)) return null;
            },
            .return_value, .return_to_caller, .fail => {},
        }
    }
    return if (predecessor_count == 0) null else result;
}

/// One bounded compiler result containing canonical dense constructors.
pub fn NormalForm(
    comptime maximum_values: usize,
    comptime maximum_blocks: usize,
    comptime maximum_constructors: usize,
    comptime maximum_environment_fields: usize,
    comptime maximum_invariant_terms: usize,
) type {
    const Set = control_ir.ValueSet(maximum_values);
    const ConstructorType = Constructor(
        maximum_environment_fields,
        maximum_invariant_terms,
    );
    const Liveness = control_ir.Liveness(maximum_values, maximum_blocks);
    const ReachabilityType = control_ir.Reachability(maximum_blocks);

    return struct {
        const Self = @This();

        constructors: [maximum_constructors]ConstructorType = undefined,
        constructor_count: usize = 0,

        /// Borrow all synthesized constructors in canonical id order.
        pub fn constructorSlice(self: *const Self) []const ConstructorType {
            return self.constructors[0..self.constructor_count];
        }

        fn equivalent(
            left: *const ConstructorType,
            right: *const ConstructorType,
        ) bool {
            if (left.kind != right.kind or
                left.source_block != right.source_block or
                left.resume_target != right.resume_target or
                left.environment_len != right.environment_len or
                left.invariant_len != right.invariant_len)
            {
                return false;
            }
            for (
                left.environmentFields(),
                right.environmentFields(),
            ) |left_field, right_field| {
                if (left_field.value != right_field.value or
                    !left_field.value_type.eql(right_field.value_type))
                {
                    return false;
                }
            }
            for (
                left.invariantTerms(),
                right.invariantTerms(),
            ) |left_term, right_term| {
                if (!left_term.eql(right_term)) return false;
            }
            return true;
        }

        fn appendConstructor(
            self: *Self,
            program: control_ir.Program,
            kind: ConstructorKind,
            source_block: control_ir.BlockId,
            resume_target: ?control_ir.BlockId,
            environment_set: Set,
            invariant: ?InvariantTerm,
        ) Error!void {
            if (self.constructor_count == maximum_constructors) {
                return error.TooManyConstructors;
            }
            var constructor: ConstructorType = .{
                .id = @intCast(self.constructor_count),
                .kind = kind,
                .source_block = source_block,
                .resume_target = resume_target,
            };
            var required = environment_set;
            if (invariant) |term| {
                term.addRequired(&required);
                if (comptime maximum_invariant_terms == 0) {
                    return error.TooManyInvariantTerms;
                }
                if (constructor.invariant_len == maximum_invariant_terms) {
                    return error.TooManyInvariantTerms;
                }
                constructor.invariants[constructor.invariant_len] = term;
                constructor.invariant_len += 1;
            }

            for (required.bits[0..program.value_types.len], 0..) |present, value_index| {
                if (!present) continue;
                if (comptime maximum_environment_fields == 0) {
                    return error.TooManyEnvironmentFields;
                }
                if (constructor.environment_len == maximum_environment_fields) {
                    return error.TooManyEnvironmentFields;
                }
                constructor.environment[constructor.environment_len] = .{
                    .value = @intCast(value_index),
                    .value_type = program.value_types[value_index],
                };
                constructor.environment_len += 1;
            }
            for (self.constructorSlice()) |*existing| {
                if (equivalent(existing, &constructor)) return;
            }
            self.constructors[self.constructor_count] = constructor;
            self.constructor_count += 1;
        }

        /// Synthesize entry, persisted block, and suspension constructors from
        /// one already computed root-reachable control graph.
        pub fn synthesizeReachable(
            program: control_ir.Program,
            reachability: ReachabilityType,
        ) Error!Self {
            const liveness = try Liveness.analyze(program);
            var result: Self = .{};
            const entry_index: usize = @intCast(program.entry);
            try result.appendConstructor(
                program,
                .entry,
                program.entry,
                program.entry,
                liveness.entry_live[entry_index],
                null,
            );

            for (program.blocks) |block| {
                if (!reachability.contains(block.id)) continue;
                const block_index: usize = @intCast(block.id);
                const invariant = immediateInvariant(
                    program,
                    block.id,
                    reachability,
                );
                if (block.id != program.entry) {
                    try result.appendConstructor(
                        program,
                        constructorKindForRole(block.role),
                        block.id,
                        block.id,
                        liveness.entry_live[block_index],
                        invariant,
                    );
                }
                switch (block.terminator) {
                    .@"suspend" => |suspension| {
                        const persists_continuation =
                            suspension.kind == .explicit_yield or
                            suspension.kind == .caller_fuel;
                        var environment = if (persists_continuation)
                            liveness.entry_live[suspension.continuation.target]
                        else
                            liveness.edgeEnvironment(
                                program,
                                suspension.continuation,
                            );
                        for (suspension.request_values) |value| {
                            _ = environment.insert(value);
                        }
                        try result.appendConstructor(
                            program,
                            constructorKindForSuspension(suspension.kind),
                            if (persists_continuation)
                                suspension.continuation.target
                            else
                                block.id,
                            suspension.continuation.target,
                            environment,
                            if (persists_continuation) null else invariant,
                        );
                    },
                    else => {},
                }
            }
            return result;
        }

        /// Synthesize from the root-reachable graph of one validated program.
        pub fn synthesize(program: control_ir.Program) Error!Self {
            const reachability = try ReachabilityType.analyze(program);
            return synthesizeReachable(program, reachability);
        }
    };
}

test "RNF splits correlated suspension paths into locally valid constructors" {
    const i32_type: control_ir.ValueType = .{ .scalar = .i32 };
    const bool_type: control_ir.ValueType = .{ .scalar = .boolean };
    const value_types = [_]control_ir.ValueType{
        i32_type,
        i32_type,
        bool_type,
        i32_type,
        i32_type,
        i32_type,
    };
    const entry_instructions = [_]control_ir.Instruction{
        .{ .kind = .constant, .result = 1 },
        .{ .kind = .compare_eq_zero, .result = 2, .operands = &.{0} },
    };
    const finish_instructions = [_]control_ir.Instruction{
        .{ .kind = .pure, .result = 5, .operands = &.{ 3, 4 } },
    };
    const continuation_arguments = [_]control_ir.EdgeArgument{
        .@"resume",
        .{ .value = 0 },
    };
    const blocks = [_]control_ir.Block{
        .{
            .id = 0,
            .parameters = &.{0},
            .instructions = &entry_instructions,
            .terminator = .{ .branch = .{
                .condition = 2,
                .then_edge = .{ .target = 1 },
                .else_edge = .{ .target = 2 },
            } },
        },
        .{
            .id = 1,
            .terminator = .{ .@"suspend" = .{
                .kind = .effect,
                .site_id = 7,
                .request_values = &.{0},
                .continuation = .{ .target = 3, .arguments = &continuation_arguments },
                .resume_type = i32_type,
            } },
        },
        .{
            .id = 2,
            .terminator = .{ .@"suspend" = .{
                .kind = .effect,
                .site_id = 8,
                .request_values = &.{0},
                .continuation = .{ .target = 3, .arguments = &continuation_arguments },
                .resume_type = i32_type,
            } },
        },
        .{
            .id = 3,
            .parameters = &.{ 3, 4 },
            .instructions = &finish_instructions,
            .terminator = .{ .return_value = 5 },
        },
    };
    const program: control_ir.Program = .{
        .label = "correlated-effect",
        .value_types = &value_types,
        .blocks = &blocks,
        .entry = 0,
        .result_type = i32_type,
    };

    const rnf = try NormalForm(16, 8, 8, 16, 4).synthesize(program);
    try std.testing.expectEqual(@as(usize, 6), rnf.constructor_count);

    const awaiting_zero = &rnf.constructors[2];
    const awaiting_nonzero = &rnf.constructors[4];
    try std.testing.expectEqual(ConstructorKind.await_effect, awaiting_zero.kind);
    try std.testing.expectEqual(@as(usize, 1), awaiting_zero.environment_len);
    try std.testing.expectEqual(@as(control_ir.ValueId, 0), awaiting_zero.environment[0].value);
    try std.testing.expectEqual(@as(usize, 1), awaiting_zero.invariant_len);
    try std.testing.expectEqual(@as(usize, 1), awaiting_nonzero.invariant_len);

    const zero_binding = [_]InvariantBinding{
        .{ .value = 0, .contents = .{ .signed = 0 } },
    };
    const nonzero_binding = [_]InvariantBinding{
        .{ .value = 0, .contents = .{ .signed = 9 } },
    };
    try awaiting_zero.validateInvariant(&zero_binding);
    try std.testing.expectError(
        error.InvariantViolation,
        awaiting_zero.validateInvariant(&nonzero_binding),
    );
    try awaiting_nonzero.validateInvariant(&nonzero_binding);
    try std.testing.expectError(
        error.InvariantViolation,
        awaiting_nonzero.validateInvariant(&zero_binding),
    );
    try std.testing.expectError(
        error.TooManyEnvironmentFields,
        NormalForm(16, 8, 8, 0, 4).synthesize(program),
    );
    try std.testing.expectError(
        error.TooManyConstructors,
        NormalForm(16, 8, 1, 16, 4).synthesize(program),
    );
    try std.testing.expectError(
        error.TooManyInvariantTerms,
        NormalForm(16, 8, 8, 16, 0).synthesize(program),
    );
}

test "all required RNF constructor classifications remain explicit" {
    inline for (.{
        ConstructorKind.entry,
        .segment_entry,
        .loop_header,
        .await_effect,
        .call_return,
        .after_handler,
        .caller_fuel_yield,
        .terminal_handoff,
    }) |_| {}
}

test "RNF hash-conses exact duplicate checkpoint futures" {
    const bool_type: control_ir.ValueType = .{ .scalar = .boolean };
    const u32_type: control_ir.ValueType = .{ .scalar = .u32 };
    const value_types = [_]control_ir.ValueType{
        bool_type,
        u32_type,
        u32_type,
        u32_type,
        u32_type,
    };
    const to_then = [_]control_ir.EdgeArgument{.{ .value = 1 }};
    const to_else = [_]control_ir.EdgeArgument{.{ .value = 1 }};
    const then_checkpoint = [_]control_ir.EdgeArgument{.{ .value = 2 }};
    const else_checkpoint = [_]control_ir.EdgeArgument{.{ .value = 3 }};
    const blocks = [_]control_ir.Block{
        .{
            .id = 0,
            .parameters = &.{ 0, 1 },
            .terminator = .{ .branch = .{
                .condition = 0,
                .then_edge = .{ .target = 1, .arguments = &to_then },
                .else_edge = .{ .target = 2, .arguments = &to_else },
            } },
        },
        .{
            .id = 1,
            .parameters = &.{2},
            .terminator = .{ .@"suspend" = .{
                .kind = .caller_fuel,
                .continuation = .{
                    .target = 3,
                    .arguments = &then_checkpoint,
                },
            } },
        },
        .{
            .id = 2,
            .parameters = &.{3},
            .terminator = .{ .@"suspend" = .{
                .kind = .caller_fuel,
                .continuation = .{
                    .target = 3,
                    .arguments = &else_checkpoint,
                },
            } },
        },
        .{
            .id = 3,
            .parameters = &.{4},
            .terminator = .{ .return_value = 4 },
        },
    };
    const program: control_ir.Program = .{
        .label = "duplicate-checkpoint-futures",
        .value_types = &value_types,
        .blocks = &blocks,
        .entry = 0,
        .result_type = u32_type,
    };

    const normal_form = try NormalForm(16, 8, 8, 16, 4).synthesize(program);
    try std.testing.expectEqual(@as(usize, 5), normal_form.constructor_count);
    var checkpoint_count: usize = 0;
    for (normal_form.constructorSlice()) |constructor| {
        if (constructor.kind == .caller_fuel_yield) checkpoint_count += 1;
    }
    try std.testing.expectEqual(@as(usize, 1), checkpoint_count);
}
